/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem>, 'totalPrice' : bigint }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Consultation {
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface FAQ { 'question' : string, 'answer' : string }
export interface Order {
  'userId' : Principal,
  'orderId' : bigint,
  'timestamp' : Time,
  'items' : Array<CartItem>,
  'totalPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'benefits' : string,
  'price' : bigint,
  'ingredients' : string,
}
export interface Testimonial {
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addFAQ' : ActorMethod<[string, string], undefined>,
  'addItemToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addProduct' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addTestimonial' : ActorMethod<[string, bigint, string], undefined>,
  'getCart' : ActorMethod<[], Cart>,
  'getConsultations' : ActorMethod<[], Array<Consultation>>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeItemFromCart' : ActorMethod<[bigint], undefined>,
  'submitConsultation' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];