/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});
export const Time = IDL.Int;
export const Consultation = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const Order = IDL.Record({
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Text,
  'price' : IDL.Nat,
  'ingredients' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
  'submitConsultation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Consultation = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Order = IDL.Record({
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Text,
    'price' : IDL.Nat,
    'ingredients' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
    'submitConsultation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };